const path = {
    passwordDisabled: require('../res/images/passwordDisabled.png'),
    'back': require('../res/images/back.png'),
    'eyeIcon': require('../res/images/eyeIcon.png'),
    'Forgot Password': require('../res/images/forgotPassword.png'),
    'Reset': require('../res/images/reset.png'),
    "Verification": require('../res/images/verification.png'),
    "checkMark": require('../res/images/checkMark.png'),
    //TABS
    "HomeActive": require('../res/images/HomeActive.png'),
    "HomeInactive": require('../res/images/HomeInactive.png'),
    "inboxActive": require('../res/images/inboxActive.png'),
    "inboxInactive": require('../res/images/inbox.png'),
    "ticketActive": require('../res/images/ticketActive.png'),
    "ticketInactive": require('../res/images/ticketInactive.png'),
    "moreActive": require('../res/images/moreActive.png'),
    "moreInactive": require('../res/images/moreInactive.png'),
    //Screens
    "userIcon": require('../res/images/userIcon.png'),
    "logout": require('../res/images/logout.png'),
    "inbox": require('../res/images/inbox.png'),
    "setting": require('../res/images/setting.png'),
    "message": require('../res/images/message.png'),

    "Engine breakdown": require('../res/images/engineBreakdown.png'),
    "Empty fuel": require('../res/images/emptyFuel.png'),
    "logo": require('../res/images/logo.png'),
    "locationRed": require('../res/images/locationRed.png'),
    "locationBlue": require('../res/images/locationBlue.png'),
    "tiltArrow": require('../res/images/tiltArrow.png'),
    "backBlack": require('../res/images/backBlack.png'),
    "arrow": require('../res/images/arrow.png'),
    "swipper1": require('../res/images/swipper1.png'),
    "swipper2": require('../res/images/swipper2.png'),
    "swipper3": require('../res/images/swipper3.png'),
    "google": require('../res/images/google.png'),
    "fb": require('../res/images/fb.png'),
    "pt": require('../res/images/pt.png'),
    "kereta": require('../res/images/kereta.png'),
    "transjakarta": require('../res/images/transjakarta.png'),
    "akap": require('../res/images/akap.png'),
    "upDownArrow": require('../res/images/upDownArrow.png'),
    "filter": require('../res/images/filter.png'),
    "refresh": require('../res/images/refresh.png'),
    "indicator": require('../res/images/indicator.png'),
    "crossRed": require('../res/images/crossRed.png'),
    "arrowLeft": require('../res/images/arrowLeft.png'),
    "arrowRight": require('../res/images/arrowRight.png'),
    "warning": require('../res/images/warning.png'),
    "rate": require('../res/images/rate.png'),
    "help": require('../res/images/help.png'),
    "share": require('../res/images/share.png'),
    "currentLoc": require('../res/images/currentLoc.png'),
    "facebook": require('../res/images/facebook.png'),
    "youtube": require('../res/images/youtube.png'),
    "instagram": require('../res/images/instagram.png'),
    "whatsapp": require('../res/images/whatsapp.png'),
    "email": require('../res/images/email.png'),
    "twitter": require('../res/images/twitter.png'),
    "tickWhite": require('../res/images/tickWhite.png'),
    "indicatorSmall": require('../res/images/indicatorSmall.png'),
    "logobus": require('../res/images/logobus.png'),
    "crossYellow": require('../res/images/crossYellow.png'),
    "addGreen": require('../res/images/addGreen.png'),
    "greenCheckBox": require('../res/images/greenCheckBox.png'),
    "reservationExpired": require('../res/images/reservationExpired.png'),
    "train": require('../res/images/train.png'),
    "messageWithQues": require('../res/images/messageWithQues.png'),
    "roundCheckMark": require('../res/images/roundCheckMark.png'),

}
export default path;